# Generated by Django 4.2.11 on 2024-04-23 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='dept_name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='dept_name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='dept_name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='id',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'section_id', 'semester', 'year')},
        ),
        migrations.DeleteModel(
            name='Prereq',
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='readdb.course'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='prerequisite_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_courses', to='readdb.course'),
        ),
    ]
