# Generated by Django 4.2.11 on 2024-04-23 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readdb', '0002_prerequisite_rename_dept_name_course_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section_id',
            new_name='section_name',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'section_name', 'semester', 'year')},
        ),
    ]
