# Generated by Django 4.2.11 on 2024-04-23 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readdb', '0004_alter_takes_unique_together_takes_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teaches',
            name='course',
            field=models.ForeignKey(default='XXXXX', on_delete=django.db.models.deletion.CASCADE, to='readdb.course'),
        ),
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together={('course', 'section', 'semester', 'year', 'instructor')},
        ),
    ]
