# Generated by Django 4.2.11 on 2024-04-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readdb', '0005_alter_teaches_unique_together_teaches_course_and_more'),
    ]

    operations = [
    ]
