# Generated by Django 4.2.11 on 2024-04-26 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readdb', '0009_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_year', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readdb.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='FundingSecured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('academic_year', models.IntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readdb.instructor')),
            ],
        ),
    ]
